development:
  adapter: sqlite3
  encoding: unicode
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: tourgames_test
  pool: 5
  username: Perry
  password:
  host: localhost
  port: 5432


production:
  adapter: postgresql
  encoding: unicode
  database: tourgames_production
  pool: 5
  username: Perry
  password:
  host: localhost
  port: 5432