# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54b1768848d7bca8a80f0480e83d238aaf7e387d3d49d8d899faf1eb15166075f291313f36a3f185d4982e9f2c16f3b25ff6f3bc6b73dcc1232ba83f0dc681fc

test:
  secret_key_base: 71a4c954f34943542be310120cbb21f6429586750385368cb1fbe590d587c14190e64485ff480dcbfc722f30dd50150cfe7bd03b13abf98a4fe6957fac98b660

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
